export const PAKISTANI_CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Abbottabad",
  "Bahawalpur",
  "Sukkur",
  "Sargodha",
  "Remote (Pakistan)",
] as const;

export const PAKISTANI_UNIVERSITIES = [
  "National University of Sciences and Technology (NUST)",
  "FAST - National University of Computer and Emerging Sciences (NUCES)",
  "Lahore University of Management Sciences (LUMS)",
  "Institute of Business Administration (IBA), Karachi",
  "NED University of Engineering and Technology",
  "Dawood University of Engineering and Technology (DUET)",
  "University of Karachi (KU)",
  "University of the Punjab (PU)",
  "COMSATS University Islamabad",
  "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI)",
  "Information Technology University (ITU), Lahore",
  "Pakistan Institute of Engineering and Applied Sciences (PIEAS)",
  "University of Engineering and Technology (UET), Lahore",
  "University of Engineering and Technology (UET), Taxila",
  "Mehran University of Engineering and Technology (MUET)",
  "Habib University",
  "Aga Khan University (AKU)",
  "Quaid-i-Azam University (QAU)",
  "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology (SZABIST)",
  "Bahria University",
  "Air University",
  "National University of Modern Languages (NUML)",
  "Riphah International University",
  "Sir Syed University of Engineering and Technology (SSUET)",
  "National University of Technology (NUTECH)",
  "University of Gujrat (UOG)",
  "Government College University (GCU), Lahore",
  "Islamia College University, Peshawar",
  "University of Balochistan, Quetta",
  "Bahauddin Zakariya University (BZU), Multan",
] as const;

export const CURATED_SKILLS = [
  // Programming Languages
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C++",
  "C#",
  "Go (Golang)",
  "Rust",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "SQL",

  // Frameworks & Libraries
  "FastAPI",
  "Django",
  "Flask",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "Vue.js",
  "Angular",
  "NestJS",
  "Spring Boot",
  "ASP.NET Core",
  "Laravel",
  "Flutter",
  "React Native",

  // Databases & Caching
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "SQLite",
  "Supabase",
  "Firebase",
  "Elasticsearch",
  "Cassandra",

  // DevOps & Cloud
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud (GCP)",
  "Microsoft Azure",
  "Linux",
  "Git",
  "GitHub Actions",
  "CI/CD",
  "Terraform",
  "Nginx",
  "Ansible",

  // AI & Data Science
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "PyTorch",
  "TensorFlow",
  "Pandas",
  "NumPy",
  "Scikit-Learn",
  "LangChain",
  "Large Language Models (LLMs)",

  // Architecture & APIs
  "REST APIs",
  "GraphQL",
  "gRPC",
  "Microservices",
  "System Design",
  "Object-Oriented Programming (OOP)",
  "WebSockets",
  "Message Queues (RabbitMQ / Kafka)",

  // Frontend & UI
  "Tailwind CSS",
  "HTML5",
  "CSS3 / SCSS",
  "Redux / Zustand",
  "UI/UX Design",
  "Figma",

  // Testing & Agile
  "Unit Testing",
  "PyTest",
  "Jest / Cypress",
  "Agile / Scrum",
  "Cybersecurity",
] as const;
